[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.3"
crc = "3.0.0"
log = "0.4.17"
rand = "0.8"
serde = "1.0.152"
tokio = { version = "1.21.1", features = ["full"] }

[dev-dependencies]
tempfile = "3"
